# alb variables 
variable "project_name" {}
variable "environment" {}
variable "alb_security_group_id" {}
variable "public_subnet_az1.id" {}
variable "public_subnet_az2.id" {}
variable "target_type" {}
variable "vpc_id" {}
variable "certificate_arn" {}
